"""Build runtime context for validator/execution stages.

This file is loaded by GigaEvo's AddContext stage (`build_context`).
"""

from __future__ import annotations

import json
from typing import Any

from kernel_evo.resources.paths import get_problem_dir


def build_context() -> dict[str, Any]:
    """Load per-run config generated by `kernel_evo evolve`."""
    problem_dir = get_problem_dir()
    run_config_path = problem_dir / "run_config.json"
    if not run_config_path.exists():
        raise FileNotFoundError(
            f"Missing run config: {run_config_path}. "
            "Run `python -m kernel_evo evolve ...` to generate it."
        )

    data = json.loads(run_config_path.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise TypeError(f"Expected JSON object in {run_config_path}")
    return data
